version: "2"
virtualmachines:
- name: tf-foundations
  image: instruqt-hashicorp/tfc-workstation-1-1-4
  shell: /bin/bash -l
  machine_type: n1-standard-1
aws_accounts:
- name: TF-FOUNDATIONS
  managed_policies:
  - arn:aws:iam::aws:policy/AmazonEC2FullAccess
  - arn:aws:iam::aws:policy/AmazonVPCFullAccess
